In [5]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [6]:
a =np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
a.shape

(1, 3, 3)

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
b[1][0]=1
b[2][0]=1
b[2][1]=2
b[3][0]=1
b[3][1]=2
b[3][2]=3
b[4][0]=1
b[4][1]=2
b[4][2]=3
b[4][3]=4
b

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 2., 0., 0., 0.],
       [1., 2., 3., 0., 0.],
       [1., 2., 3., 4., 0.]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
a = np.zeros((8,8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [12]:
b = np.random.random((5,5))
b

array([[0.49466023, 0.49010728, 0.30431042, 0.63295055, 0.94055631],
       [0.63754017, 0.86200615, 0.684854  , 0.64830055, 0.80679481],
       [0.72993821, 0.98701694, 0.49940313, 0.38059669, 0.69914736],
       [0.68542999, 0.96089848, 0.13946435, 0.04867925, 0.04081769],
       [0.43432074, 0.29984941, 0.7447468 , 0.64948526, 0.27117851]])

In [13]:
bmax=b.max()
bmin=b.min()
b=(b-bmin)/(bmax-bmin)
print("Normalization Done")
b

Normalization Done


array([[0.47964796, 0.47483612, 0.27847488, 0.62580145, 0.95089762],
       [0.63065203, 0.86788111, 0.68065611, 0.64202425, 0.80953046],
       [0.7283038 , 1.        , 0.48466054, 0.35909878, 0.69576219],
       [0.68126486, 0.97239644, 0.10425569, 0.00830857, 0.        ],
       [0.41587758, 0.27376022, 0.74395441, 0.64327631, 0.2434591 ]])

# 5.  How to find common values between two arrays?

In [15]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[10,100,20],[40,400,50]])
print(arr1)
print(arr2)

[[10 20 30]
 [40 50 60]]
[[ 10 100  20]
 [ 40 400  50]]


In [17]:
print(np.intersect1d(arr1,arr2))

[10 20 40 50]


# 6.How to get the dates of yesterday, today and tomorrow?

In [18]:
yesterday=np.datetime64('today','D')-np.timedelta64(1, 'D')
print("Yesterday date:",yesterday)

Yesterday date: 2020-07-27


In [19]:
today=np.datetime64('today','D')
print("today's date:",today)

today's date: 2020-07-28


In [21]:
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tommorow's date:",tomorrow)

tommorow's date: 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [23]:
l=np.random.randint(0,2,5)
l

array([0, 0, 0, 1, 1])

In [24]:
m=np.random.randint(0,2,5)
m

array([1, 0, 0, 1, 1])

In [25]:
array_check=np.allclose(l,m)
array_check

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [26]:
n=np.random.random(10)
n

array([0.28767825, 0.97112705, 0.85139504, 0.43328641, 0.91167308,
       0.91932139, 0.52608751, 0.68755117, 0.28937172, 0.95912231])

In [27]:
n.argmax()

1

In [28]:
n[n.argmax()]=0
print("Replaced the maximum value by 0")
n

Replaced the maximum value by 0


array([0.28767825, 0.        , 0.85139504, 0.43328641, 0.91167308,
       0.91932139, 0.52608751, 0.68755117, 0.28937172, 0.95912231])

# 9. How to print all the values of an array?

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

# 10.Subtract the mean of each row of a matrix

In [34]:
y=np.random.rand(4,5)
y

array([[0.18796094, 0.65460539, 0.22050936, 0.05028514, 0.17305302],
       [0.43059167, 0.10200817, 0.46470985, 0.50283778, 0.91790371],
       [0.88627172, 0.97903617, 0.27756844, 0.69951594, 0.68931982],
       [0.18899317, 0.35585085, 0.40292738, 0.71167454, 0.28712465]])

In [35]:
print("Subtraced the mean of each row:")
y=y-y.mean(axis=1,keepdims=True)
y

Subtraced the mean of each row:


array([[-0.06932183,  0.39732263, -0.03677341, -0.20699763, -0.08422975],
       [-0.05301857, -0.38160206, -0.01890039,  0.01922754,  0.43429348],
       [ 0.1799293 ,  0.27269376, -0.42877398, -0.00682648, -0.0170226 ],
       [-0.20032095, -0.03346327,  0.01361326,  0.32236042, -0.10218947]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [37]:
l = np.random.random((2,2))
l

array([[0.64355357, 0.97906657],
       [0.29494526, 0.23016602]])

In [38]:
m=np.ones((2,2))
m

array([[1., 1.],
       [1., 1.]])

In [39]:
l+=m
l

array([[1.64355357, 1.97906657],
       [1.29494526, 1.23016602]])

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [49]:
a = np.random.randint(0,10,50)
a

array([4, 3, 9, 1, 5, 4, 9, 3, 7, 6, 1, 7, 7, 9, 6, 1, 4, 8, 7, 2, 9, 9,
       0, 1, 1, 8, 2, 5, 2, 4, 3, 1, 3, 9, 9, 1, 9, 7, 5, 1, 5, 6, 8, 9,
       5, 9, 8, 5, 0, 2])

In [50]:
a.argmax()

2

In [51]:
np.bincount(a).argmax()

9

# 14.How to get the n largest values of an array

In [52]:
np.random.shuffle(a)

In [53]:
n=1
print(a[np.argsort(a)[-n:]])

[9]


# 15.How to create a record array from a regular array?

In [55]:
a = np.array([('Red',34.9,40),('Yellow',67.3,78)])
a

array([['Red', '34.9', '40'],
       ['Yellow', '67.3', '78']], dtype='<U6')

In [56]:
result=np.core.records.fromarrays(a.T,names='a,b')
result

rec.array([('Red', '34.9', '40'), ('Yellow', '67.3', '78')],
          dtype=[('a', '<U6'), ('b', '<U6'), ('f2', '<U6')])